In [17]:
import numpy as np
version = 2
seed = version
import pickle

In [18]:
np.random.seed(seed)
# a = np.arange(10)

In [19]:
cifar_inds = np.arange(50000)
ti_inds = np.arange(500000)


In [20]:
np.random.seed(seed)
np.random.shuffle(cifar_inds)
np.random.seed(seed)
np.random.shuffle(ti_inds)

In [21]:
cifar_odd = cifar_inds[0:25000]
cifar_even = cifar_inds[25000:]

ti_odd = ti_inds[0:250000]
ti_even = ti_inds[250000:]

In [9]:
print(a)

[1 3 4 5 0 8 6 9 7 2]


In [10]:
a[0:5]

array([1, 3, 4, 5, 0])

In [11]:
a[5:]

array([8, 6, 9, 7, 2])

In [22]:
ti_odd_file = '../data/cifar-10-batches-py/odd_ti_list_v' + str(version)
ti_even_file = '../data/cifar-10-batches-py/even_ti_list_v' + str(version)
cifar_odd_file = '../data/cifar-10-batches-py/odd_cifar_list_v' + str(version)
cifar_even_file = '../data/cifar-10-batches-py/even_cifar_list_v' + str(version)
with open (ti_odd_file, 'wb') as fp:
    pickle.dump(ti_odd, fp)
with open (ti_even_file, 'wb') as fp:
    pickle.dump(ti_even, fp)
with open (cifar_odd_file, 'wb') as fp:
    pickle.dump(cifar_odd, fp)
with open (cifar_even_file, 'wb') as fp:
    pickle.dump(cifar_even, fp)    

In [24]:
cifar_odd[0:10]

array([23656, 27442, 40162,  8459,  8051, 42404,    89,  1461, 13519,
       42536])

In [25]:
ti_even[0:10]

array([], dtype=int64)